name: Build and Push Container
run-name: Building weather-alerts 🚀
on: [push, workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Test
        run: uv run pytest -x -vv -s

      - name: Build Docker image
        run: docker build -t weather-alerts:latest .

      - name: Tag Docker image
        run: |
          docker tag weather-alerts:latest ${{ vars.DOCKER_REGISTRY }}/weather-alerts:latest
          docker tag weather-alerts:latest ${{ vars.DOCKER_REGISTRY }}/weather-alerts:uv-${{ steps.setup-uv.outputs.uv-version }}

      - name: Log in to Docker registry
        if: ${{ vars.HAS_DOCKER_CREDS == 'true' }}
        env:
          HAS_DOCKER_CREDS: ${{ secrets.DOCKER_PASSWORD != '' }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ vars.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/weather-alerts:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/weather-alerts:uv-${{ steps.setup-uv.outputs.uv-version }}
